# Generated by Django 4.2.3 on 2023-07-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category_publish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='publish',
        ),
        migrations.AlterField(
            model_name='product',
            name='colour',
            field=models.CharField(choices=[('Tilla', 'Tilla'), ('Kumush', 'Kumush'), ('Bronza', 'Bronza')], max_length=150, verbose_name='Rangi/Material'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default="Bu yerda tez orada malumot paydo bo'ladi!", verbose_name='Batafsil'),
        ),
    ]
