# Generated by Django 4.2.3 on 2023-07-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_category_publish_alter_product_colour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='colour',
            field=models.CharField(choices=[('Tilla', 'Tilla'), ('Kumush', 'Kumush'), ('Bronza', 'Bronza'), ('Platina', 'Platina'), ('Koja', 'Koja'), ('Magnitli', 'Magnitli')], max_length=150, verbose_name='Rangi/Material'),
        ),
    ]
