# Generated by Django 4.2.3 on 2023-07-25 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_shippingaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='zip_code',
            new_name='zipcode',
        ),
    ]
