# Generated by Django 4.2.3 on 2023-07-25 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_rename_zip_code_shippingaddress_zipcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'verbose_name': 'Savatdagi mahsulot', 'verbose_name_plural': 'Savatdagi mahsulotlar'},
        ),
    ]
