# Generated by Django 4.2.3 on 2023-07-26 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0010_alter_orderproduct_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Izoh')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='izoh qoldirilgan')),
                ('publish', models.BooleanField(default=True, verbose_name='Chop etish')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='avtor')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'talab',
                'verbose_name_plural': 'talablar',
            },
        ),
    ]
