# Generated by Django 4.2.3 on 2023-07-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_contacts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='product',
        ),
        migrations.AddField(
            model_name='contacts',
            name='contact',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
