# Generated by Django 4.2.3 on 2023-08-01 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0012_remove_contacts_product_contacts_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='avtor'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='contact',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
