# Generated by Django 4.2.3 on 2023-08-01 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_contacts_author_alter_contacts_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='author',
        ),
    ]
