# Generated by Django 4.2.3 on 2023-08-01 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_remove_contacts_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='publish',
        ),
    ]
