# Generated by Django 4.2.3 on 2023-08-01 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0016_alter_contacts_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Avtor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='publish',
            field=models.BooleanField(default=True, verbose_name='Chop etish'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='contact',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
